// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pbparser.proto

package pbparser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 요청할 설정 키
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Req) Reset() {
	*x = Req{}
	mi := &file_pbparser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_pbparser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_pbparser_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // 설정 값
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resp) Reset() {
	*x = Resp{}
	mi := &file_pbparser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_pbparser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_pbparser_proto_rawDescGZIP(), []int{1}
}

func (x *Resp) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *Resp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pbparser_proto protoreflect.FileDescriptor

const file_pbparser_proto_rawDesc = "" +
	"\n" +
	"\x0epbparser.proto\x12\bpbparser\"\x17\n" +
	"\x03Req\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"0\n" +
	"\x04Resp\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2}\n" +
	"\aParserx\x12$\n" +
	"\x03ENV\x12\r.pbparser.Req\x1a\x0e.pbparser.Resp\x12%\n" +
	"\x04JSON\x12\r.pbparser.Req\x1a\x0e.pbparser.Resp\x12%\n" +
	"\x04YAML\x12\r.pbparser.Req\x1a\x0e.pbparser.RespB\x10Z\x0eproto/pbparserb\x06proto3"

var (
	file_pbparser_proto_rawDescOnce sync.Once
	file_pbparser_proto_rawDescData []byte
)

func file_pbparser_proto_rawDescGZIP() []byte {
	file_pbparser_proto_rawDescOnce.Do(func() {
		file_pbparser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbparser_proto_rawDesc), len(file_pbparser_proto_rawDesc)))
	})
	return file_pbparser_proto_rawDescData
}

var file_pbparser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbparser_proto_goTypes = []any{
	(*Req)(nil),  // 0: pbparser.Req
	(*Resp)(nil), // 1: pbparser.Resp
}
var file_pbparser_proto_depIdxs = []int32{
	0, // 0: pbparser.Parserx.ENV:input_type -> pbparser.Req
	0, // 1: pbparser.Parserx.JSON:input_type -> pbparser.Req
	0, // 2: pbparser.Parserx.YAML:input_type -> pbparser.Req
	1, // 3: pbparser.Parserx.ENV:output_type -> pbparser.Resp
	1, // 4: pbparser.Parserx.JSON:output_type -> pbparser.Resp
	1, // 5: pbparser.Parserx.YAML:output_type -> pbparser.Resp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbparser_proto_init() }
func file_pbparser_proto_init() {
	if File_pbparser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbparser_proto_rawDesc), len(file_pbparser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbparser_proto_goTypes,
		DependencyIndexes: file_pbparser_proto_depIdxs,
		MessageInfos:      file_pbparser_proto_msgTypes,
	}.Build()
	File_pbparser_proto = out.File
	file_pbparser_proto_goTypes = nil
	file_pbparser_proto_depIdxs = nil
}
